// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFmhEBa8bZFa0ccAPvkkdpOcHN6aEWVpY',
    appId: '1:697512189134:web:92237672bb6d45e0cc849f',
    messagingSenderId: '697512189134',
    projectId: 'plasticpunk-e6622',
    authDomain: 'plasticpunk-e6622.firebaseapp.com',
    storageBucket: 'plasticpunk-e6622.appspot.com',
    measurementId: 'G-BEDJHFGZTQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZxu64YLpxkIZ80gQbVpxdhZFJ1WmQHx8',
    appId: '1:697512189134:android:a3581640e9489576cc849f',
    messagingSenderId: '697512189134',
    projectId: 'plasticpunk-e6622',
    storageBucket: 'plasticpunk-e6622.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDy5PQGRkugNKoRoDqJbnC1OB_QehqItzk',
    appId: '1:697512189134:ios:6e5db8d239c9c0f8cc849f',
    messagingSenderId: '697512189134',
    projectId: 'plasticpunk-e6622',
    storageBucket: 'plasticpunk-e6622.appspot.com',
    iosBundleId: 'co.cococode.plasticPunk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDy5PQGRkugNKoRoDqJbnC1OB_QehqItzk',
    appId: '1:697512189134:ios:eff3c8b91072f3f8cc849f',
    messagingSenderId: '697512189134',
    projectId: 'plasticpunk-e6622',
    storageBucket: 'plasticpunk-e6622.appspot.com',
    iosBundleId: 'co.cococode.plasticPunk.RunnerTests',
  );
}
