import 'package:plastic_punk/state/game/levels/level.dart';
import 'package:plastic_punk/state/game/logic/technology_tree.dart';
import 'package:plastic_punk/state/game/messages/messages.dart';
import 'package:plastic_punk/utils/constants/tiles.dart';

abstract class Levels {
  static final levels = [
    const Level(
      level: 1,
      name: 'The begining',
      description: 'Build a town hall and start cleaning.',
      map: 'level_1.tmx',
      introMessage: Messages.level1Message,
      enabledBuildings: [AppTiles.townHall],
      enabledTechnologies: [],
      requiredBuildings: [AppTiles.townHall],
      requiredTechnologies: [],
      requiredCleanup: true,
      existingTechnologies: [],
    ),
    Level(
      level: 2,
      name: 'Start a community',
      description: 'Start building your community and continue to cleaning up.',
      map: 'level_2.tmx',
      introMessage: Messages.level2Message,
      enabledBuildings: [AppTiles.townHall, ...AppTiles.transportationTiles, AppTiles.garden, AppTiles.house],
      enabledTechnologies: [],
      requiredBuildings: [AppTiles.townHall, AppTiles.garden, AppTiles.house],
      requiredTechnologies: [],
      requiredCleanup: true,
      existingTechnologies: [],
    ),
    Level(
      level: 3,
      name: 'Start researching',
      description: 'Start researching for new technologies and continue to clean up the pollution.',
      map: 'level_3.tmx',
      introMessage: Messages.level3Message,
      enabledBuildings: [
        AppTiles.townHall,
        ...AppTiles.transportationTiles,
        AppTiles.garden,
        AppTiles.house,
        AppTiles.researchCentre,
      ],
      enabledTechnologies: [TechnologyType.plasticsReduce],
      requiredBuildings: [AppTiles.townHall, AppTiles.researchCentre],
      requiredTechnologies: [TechnologyType.plasticsReduce],
      requiredCleanup: true,
      existingTechnologies: [],
    ),
    Level(
      level: 4,
      name: 'Begin to recycle',
      description: 'Research recycling and start turning waste into resources.',
      map: 'level_4.tmx',
      introMessage: Messages.level4Message,
      enabledBuildings: [
        AppTiles.townHall,
        ...AppTiles.transportationTiles,
        AppTiles.garden,
        AppTiles.house,
        AppTiles.researchCentre,
        AppTiles.plasticsEnergy,
        AppTiles.plasticRecycling,
      ],
      enabledTechnologies: [
        TechnologyType.plasticsReduce,
        TechnologyType.plasticsReuse,
        TechnologyType.plasticsRecycle,
      ],
      requiredBuildings: [AppTiles.townHall, AppTiles.plasticsEnergy, AppTiles.plasticRecycling],
      requiredTechnologies: [
        TechnologyType.plasticsReduce,
        TechnologyType.plasticsReuse,
        TechnologyType.plasticsRecycle,
      ],
      requiredCleanup: true,
      existingTechnologies: [TechnologyType.plasticsReduce],
    ),
    Level(
      level: 5,
      name: 'Ensure drinking water',
      description: 'Start cleaning up the waters to bring back health to the environment.',
      map: 'level_5.tmx',
      introMessage: Messages.level5Message,
      enabledBuildings: [
        AppTiles.townHall,
        ...AppTiles.transportationTiles,
        AppTiles.garden,
        AppTiles.house,
        AppTiles.researchCentre,
        AppTiles.plasticsEnergy,
        AppTiles.plasticRecycling,
        AppTiles.waterTreatment,
      ],
      enabledTechnologies: [
        TechnologyType.plasticsReduce,
        TechnologyType.plasticsReuse,
        TechnologyType.plasticsRecycle,
        TechnologyType.waterTreatment,
      ],
      requiredBuildings: [AppTiles.townHall, AppTiles.waterTreatment],
      requiredTechnologies: [
        TechnologyType.waterTreatment,
      ],
      requiredCleanup: true,
      existingTechnologies: [
        TechnologyType.plasticsReduce,
        TechnologyType.plasticsReuse,
        TechnologyType.plasticsRecycle,
      ],
    ),
    Level(
      level: 6,
      name: 'Improve the health',
      description: 'Take care of the health of the citizens and the environment.',
      map: 'level_6.tmx',
      introMessage: Messages.level6Message,
      enabledBuildings: [
        AppTiles.townHall,
        ...AppTiles.transportationTiles,
        AppTiles.garden,
        AppTiles.house,
        AppTiles.researchCentre,
        AppTiles.plasticsEnergy,
        AppTiles.plasticRecycling,
        AppTiles.waterTreatment,
        AppTiles.park,
        AppTiles.solarPanels,
      ],
      enabledTechnologies: [
        TechnologyType.plasticsReduce,
        TechnologyType.plasticsReuse,
        TechnologyType.plasticsRecycle,
        TechnologyType.waterTreatment,
      ],
      requiredBuildings: [AppTiles.townHall, AppTiles.park, AppTiles.solarPanels],
      requiredTechnologies: [
        TechnologyType.waterTreatment,
      ],
      requiredCleanup: true,
      existingTechnologies: [
        TechnologyType.plasticsReduce,
        TechnologyType.plasticsReuse,
        TechnologyType.plasticsRecycle,
        TechnologyType.waterTreatment,
      ],
    ),
    Level(
      level: 7,
      name: 'Clean up the oceans',
      description: 'Start cleaning up the oceans and bring back life to the seas.',
      map: 'level_7.tmx',
      introMessage: Messages.level7Message,
      enabledBuildings: [
        AppTiles.townHall,
        ...AppTiles.transportationTiles,
        AppTiles.garden,
        AppTiles.house,
        AppTiles.researchCentre,
        AppTiles.plasticsEnergy,
        AppTiles.plasticRecycling,
        AppTiles.waterTreatment,
        AppTiles.park,
        AppTiles.solarPanels,
        AppTiles.waterCleanup,
      ],
      enabledTechnologies: [
        TechnologyType.plasticsReduce,
        TechnologyType.plasticsReuse,
        TechnologyType.plasticsRecycle,
        TechnologyType.waterTreatment,
        TechnologyType.waterCleanup,
      ],
      requiredBuildings: [AppTiles.townHall, AppTiles.waterCleanup],
      requiredTechnologies: [
        TechnologyType.waterCleanup,
      ],
      requiredCleanup: true,
      existingTechnologies: [
        TechnologyType.plasticsReduce,
        TechnologyType.plasticsReuse,
        TechnologyType.plasticsRecycle,
        TechnologyType.waterTreatment,
      ],
    ),
    Level(
      level: 8,
      name: 'Change minds',
      description: 'Start educating the others and change their minds to a more sustainable way of living.',
      map: 'level_8.tmx',
      introMessage: Messages.level8Message,
      enabledBuildings: [
        AppTiles.townHall,
        ...AppTiles.transportationTiles,
        AppTiles.garden,
        AppTiles.house,
        AppTiles.researchCentre,
        AppTiles.plasticsEnergy,
        AppTiles.plasticRecycling,
        AppTiles.waterTreatment,
        AppTiles.park,
        AppTiles.solarPanels,
        AppTiles.waterCleanup,
        AppTiles.educationCentre,
      ],
      enabledTechnologies: [
        TechnologyType.plasticsReduce,
        TechnologyType.plasticsReuse,
        TechnologyType.plasticsRecycle,
        TechnologyType.waterTreatment,
        TechnologyType.waterCleanup,
      ],
      requiredBuildings: [AppTiles.townHall, AppTiles.educationCentre],
      requiredTechnologies: [],
      requiredCleanup: true,
      existingTechnologies: [
        TechnologyType.plasticsReduce,
        TechnologyType.plasticsReuse,
        TechnologyType.plasticsRecycle,
        TechnologyType.waterTreatment,
        TechnologyType.waterCleanup,
      ],
    ),
    Level(
      level: 9,
      name: 'The final challenge',
      description: 'The final challenge to save the world.',
      map: 'level_9.tmx',
      introMessage: Messages.level9Message,
      enabledBuildings: [
        AppTiles.townHall,
        ...AppTiles.transportationTiles,
        AppTiles.garden,
        AppTiles.house,
        AppTiles.researchCentre,
        AppTiles.plasticsEnergy,
        AppTiles.plasticRecycling,
        AppTiles.waterTreatment,
        AppTiles.park,
        AppTiles.solarPanels,
        AppTiles.waterCleanup,
        AppTiles.educationCentre,
      ],
      enabledTechnologies: [
        TechnologyType.plasticsReduce,
        TechnologyType.plasticsReuse,
        TechnologyType.plasticsRecycle,
        TechnologyType.waterTreatment,
        TechnologyType.waterCleanup,
      ],
      requiredBuildings: [],
      requiredTechnologies: [],
      requiredCleanup: true,
      existingTechnologies: [],
    ),
  ];
}
